# Generated by Django 5.2 on 2025-06-28 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Credential",
            new_name="Credentials",
        ),
    ]
