# Generated by Django 5.2 on 2025-06-28 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0002_rename_credential_credentials"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Credentials",
            new_name="Credential",
        ),
    ]
