# Generated by Django 5.2 on 2025-06-28 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0003_rename_credentials_credential"),
    ]

    operations = [
        migrations.RenameField(
            model_name="credential",
            old_name="cliend_id",
            new_name="client_id",
        ),
    ]
