# Generated by Django 5.2 on 2025-06-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0004_rename_cliend_id_credential_client_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credential",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
