# Generated by Django 5.2 on 2025-06-28 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0005_alter_credential_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Token",
        ),
    ]
