# Generated by Django 5.2 on 2025-06-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0007_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="token",
            old_name="secret",
            new_name="access_token",
        ),
    ]
