# Generated by Django 5.2 on 2025-06-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0008_rename_secret_token_access_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="token",
            old_name="type",
            new_name="token_type",
        ),
    ]
