# Generated by Django 5.2 on 2025-06-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0009_rename_type_token_token_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpotifyUser",
            fields=[
                (
                    "id",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
