# Generated by Django 5.2 on 2025-06-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0010_spotifyuser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spotifyuser",
            options={
                "verbose_name": "SpotifyUser",
                "verbose_name_plural": "SpotifyUsers",
            },
        ),
    ]
